name: flutter_math_fork
description: Fast TeX math equation rendering for Flutter, with selectable math support and maintained compatibility for current Flutter releases.
version: 0.8.0
homepage: https://github.com/simpleclub/flutter_math
repository: https://github.com/simpleclub/flutter_math
issue_tracker: https://github.com/simpleclub/flutter_math/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.2
  provider: ^6.1.5+1
  collection: ^1.19.1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: KaTeX_Main
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Italic.ttf
          style: italic
        - asset: lib/katex_fonts/fonts/KaTeX_Main-Bold.ttf
          weight: 700
        - asset: lib/katex_fonts/fonts/KaTeX_Main-BoldItalic.ttf
          weight: 700
          style: italic
    - family: KaTeX_Math
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Math-Italic.ttf
          style: italic
        - asset: lib/katex_fonts/fonts/KaTeX_Math-BoldItalic.ttf
          weight: 700
          style: italic
    - family: KaTeX_AMS
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_AMS-Regular.ttf
    - family: KaTeX_Caligraphic
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Caligraphic-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Caligraphic-Bold.ttf
          weight: 700
    - family: KaTeX_Fraktur
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Fraktur-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_Fraktur-Bold.ttf
          weight: 700
    - family: KaTeX_SansSerif
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Regular.ttf
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Bold.ttf
          weight: 700
        - asset: lib/katex_fonts/fonts/KaTeX_SansSerif-Italic.ttf
          style: italic
    - family: KaTeX_Script
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Script-Regular.ttf
    - family: KaTeX_Typewriter
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Typewriter-Regular.ttf
    - family: KaTeX_Size1
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size1-Regular.ttf
    - family: KaTeX_Size2
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size2-Regular.ttf
    - family: KaTeX_Size3
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size3-Regular.ttf
    - family: KaTeX_Size4
      fonts:
        - asset: lib/katex_fonts/fonts/KaTeX_Size4-Regular.ttf
